<meta charset="UTF-8">
<title>RateMyShawarma</title>         <!-- Browser tab title -->
<link rel="icon" href="media/browser_icon.jpg">       <!-- Browser tab icon -->
<link rel="stylesheet" type="text/css" href="style2.css">        <!-- Importing CSS file -->
<script type="text/javascript" src="search.js"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&callback=initialize"></script>
<style>
    #map { height: 100%; }
</style>