<div class="nav-logo">
    <h4>RateMyShawarma</h4>
</div>
<ul class="nav-links">
    <!-- We set up the nav bar here. The Home page is linked to this file, search.html-->
    <li><a href="search.php">Home</a></li>
    <li><a href="westdale_results.php">Search Results</a></li>
    <li><a href="add_restaurant.php">Add Restaurant</a></li> <!--The Submit review page is linied to submission.html-->
    <li><a href="login.php">Login/Register</a></li> <!--The login page is linked to login.html-->
</ul>